[package]
name = "scrappy"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
scraper = "0.19.0"
tokio = { version = "1", features = ["full"] }
lazy_static = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
ammonia = "4.0.0"
readability = "0.3.0"
html2text = "0.12.5"
url = { workspace = true }
tempfile = "3.10.1"
paste = "1.0.15"
html5ever = "0.27.0"
markup5ever_rcdom = "0.3.0"
encoding_rs = "0.8.34"
thiserror = "1.0.62"
