[package]
name = "demo"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
scrapyy = { path = "../scrapyy" }
tokio = { version = "1", features = ["full"] }

[lints]
workspace = true
